### ISSUE TITLE
[Bug]: Cannot find module when using Yarn PnP

### ISSUE THREAD

**Issue by AkiraVoid** [sheerlox/import-from-esm#158]
I am using semantic-release 24 within an ESM project, and it uses this package to find modules.

The semantic-release reports `✘  An error occurred while running semantic-release: Error: Cannot find module 'conventional-changelog-conventionalcommits'` and then I searched the Internet, having no idea what should be done to fix this problem. The (almost) same build was available back to semantic-release 21, and after I upgrade it to 22, the problem appears. The output traces mentioned this package, so I decided to report this as a bug of this repo.

I am using node 22 ltsc with yarn 4.9.2, here's my config:

`package.json:`
```json
{
  "name": "akiravoid-atlas",
  "type": "module",
  "private": true,
  "packageManager": "yarn@4.9.2",
  "devDependencies": {
    "@babel/core": "^7.28.0",
    "@babel/plugin-syntax-typescript": "^7.27.1",
    "@eslint/eslintrc": "^3.3.1",
    "@eslint/js": "^9.33.0",
    "@griffel/tag-processor": "^1.0.13",
    "@griffel/vite-plugin": "^0.1.13",
    "@playwright/test": "^1.54.2",
    "@semantic-release/changelog": "^6.0.3",
    "@semantic-release/exec": "^7.1.0",
    "@semantic-release/git": "^10.0.1",
    "@types/babel__core": "^7",
    "@types/node": "^24.2.1",
    "@types/react": "<19",
    "@types/react-dom": "<19",
    "@types/scheduler": "^0.26.0",
    "@vitejs/plugin-react": "^4.7.0",
    "conventional-changelog-conventionalcommits": "^9.1.0",
    "cspell": "^9.2.0",
    "eslint": "^9.33.0",
    "eslint-config-prettier": "^10.1.8",
    "eslint-plugin-node": "^11.1.0",
    "husky": "^9.1.7",
    "lint-staged": "^16.1.5",
    "playwright": "^1.54.2",
    "prettier": "^3.6.2",
    "rollup": "^4.46.2",
    "semantic-release": "^24.2.7",
    "typescript": "^5.9.2",
    "typescript-eslint": "^8.39.1",
    "vite": "^7.1.1"
  },
  "dependencies": {
   ...
  }
}
```

`release.config.js`:
```js
/**
 * @type {import('semantic-release').GlobalConfig}
 */
const config = {
  plugins: [
    [
      '@semantic-release/commit-analyzer',
      {
        preset: 'conventionalcommits',
      },
    ],
    [
      '@semantic-release/release-notes-generator',
      {
        preset: 'conventionalcommits',
      },
    ],
    '@semantic-release/changelog',
    [
      '@semantic-release/npm',
      {
        npmPublish: false,
      },
    ],
    [
      '@semantic-release/exec',
      {
        prepareCmd:
          'yarn build:ci --version ${nextRelease.version} --no-must-find-assets',
        publishCmd: 'docker push -a ghcr.io/image',
      },
    ],
    '@semantic-release/git',
    [
      '@semantic-release/github',
      {
        assets: [
          {
            path: 'release.zip',
            name: '${nextRelease.version}.zip',
            label: 'Release Pack ${nextRelease.version}',
          },
        ],
      },
    ],
  ],
};

export default config;
```

And the output with `DEBUG=impor-from-esm`:
```bash
...
[5:23:40 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[5:23:40 PM] [semantic-release] › ℹ  No git tag version found on branch main
[5:23:40 PM] [semantic-release] › ℹ  No previous release found, retrieving all commits
[5:23:40 PM] [semantic-release] › ℹ  Found 13 commits since last release
[5:23:40 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
  import-from-esm Executing importFrom('/workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib', 'conventional-changelog-conventionalcommits') +0ms
  import-from-esm 'conventional-changelog-conventionalcommits' is not a file module +0ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js' +0ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits' imported from /workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js +3ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits.js' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js' +0ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits.js' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits.js' imported from /workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js +3ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits.mjs' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js' +0ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits.mjs' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits.mjs' imported from /workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js +3ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits.cjs' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js' +0ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits.cjs' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits.cjs' imported from /workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js +3ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits.json' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js' +0ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits.json' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits.json' imported from /workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js +3ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits/index.js' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js' +0ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits/index.js' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits' imported from /workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js +2ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits/index.mjs' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js' +0ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits/index.mjs' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits' imported from /workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js +2ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits/index.cjs' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js' +0ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits/index.cjs' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits' imported from /workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js +3ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits/index.json' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js' +0ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits/index.json' from 'file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits' imported from /workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/noop.js +2ms
  import-from-esm Cannot find module 'conventional-changelog-conventionalcommits' +0ms
  import-from-esm Executing importFrom('/workspaces/Atlas', 'conventional-changelog-conventionalcommits') +0ms
  import-from-esm 'conventional-changelog-conventionalcommits' is not a file module +0ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits' from 'file:///workspaces/Atlas/noop.js' +0ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits' from 'file:///workspaces/Atlas/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits' imported from /workspaces/Atlas/noop.js +2ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits.js' from 'file:///workspaces/Atlas/noop.js' +0ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits.js' from 'file:///workspaces/Atlas/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits.js' imported from /workspaces/Atlas/noop.js +1ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits.mjs' from 'file:///workspaces/Atlas/noop.js' +0ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits.mjs' from 'file:///workspaces/Atlas/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits.mjs' imported from /workspaces/Atlas/noop.js +1ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits.cjs' from 'file:///workspaces/Atlas/noop.js' +0ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits.cjs' from 'file:///workspaces/Atlas/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits.cjs' imported from /workspaces/Atlas/noop.js +1ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits.json' from 'file:///workspaces/Atlas/noop.js' +0ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits.json' from 'file:///workspaces/Atlas/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits.json' imported from /workspaces/Atlas/noop.js +1ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits/index.js' from 'file:///workspaces/Atlas/noop.js' +0ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits/index.js' from 'file:///workspaces/Atlas/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits' imported from /workspaces/Atlas/noop.js +0ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits/index.mjs' from 'file:///workspaces/Atlas/noop.js' +0ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits/index.mjs' from 'file:///workspaces/Atlas/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits' imported from /workspaces/Atlas/noop.js +1ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits/index.cjs' from 'file:///workspaces/Atlas/noop.js' +0ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits/index.cjs' from 'file:///workspaces/Atlas/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits' imported from /workspaces/Atlas/noop.js +0ms
  import-from-esm Trying to resolve 'conventional-changelog-conventionalcommits/index.json' from 'file:///workspaces/Atlas/noop.js' +1ms
  import-from-esm Failed to resolve 'conventional-changelog-conventionalcommits/index.json' from 'file:///workspaces/Atlas/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'conventional-changelog-conventionalcommits' imported from /workspaces/Atlas/noop.js +0ms
  import-from-esm Cannot find module 'conventional-changelog-conventionalcommits' +0ms
[5:23:40 PM] [semantic-release] › ✘  Failed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[5:23:40 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Cannot find module 'conventional-changelog-conventionalcommits'
    at importFrom (file:///root/.yarn/berry/cache/import-from-esm-npm-2.0.0-8866147795-10c0.zip/node_modules/import-from-esm/index.js:114:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async default (file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/load-parser-config.js:25:63)
    at async analyzeCommits (file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/index.js:31:18)
    at async validator (file:///root/.yarn/berry/cache/semantic-release-npm-24.2.7-4c91c83acb-10c0.zip/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
    at async file:///root/.yarn/berry/cache/semantic-release-npm-24.2.7-4c91c83acb-10c0.zip/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
    at async Promise.all (index 0)
    at async next (file:///root/.yarn/berry/cache/p-reduce-npm-3.0.0-a4e7df18a7-10c0.zip/node_modules/p-reduce/index.js:15:44) {
  code: 'MODULE_NOT_FOUND',
  pluginName: '@semantic-release/commit-analyzer'
}
Error: Cannot find module 'conventional-changelog-conventionalcommits'
    at importFrom (file:///root/.yarn/berry/cache/import-from-esm-npm-2.0.0-8866147795-10c0.zip/node_modules/import-from-esm/index.js:114:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async default (file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/lib/load-parser-config.js:25:63)
    at async analyzeCommits (file:///workspaces/Atlas/.yarn/__virtual__/@semantic-release-commit-analyzer-virtual-4de4f122a9/3/root/.yarn/berry/cache/@semantic-release-commit-analyzer-npm-13.0.1-11c96deec0-10c0.zip/node_modules/@semantic-release/commit-analyzer/index.js:31:18)
    at async validator (file:///root/.yarn/berry/cache/semantic-release-npm-24.2.7-4c91c83acb-10c0.zip/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
    at async file:///root/.yarn/berry/cache/semantic-release-npm-24.2.7-4c91c83acb-10c0.zip/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
    at async Promise.all (index 0)
    at async next (file:///root/.yarn/berry/cache/p-reduce-npm-3.0.0-a4e7df18a7-10c0.zip/node_modules/p-reduce/index.js:15:44) {
  code: 'MODULE_NOT_FOUND',
  pluginName: '@semantic-release/commit-analyzer'
```

**Comment by BinToss** [comment]
Unplugging did NOT help.
`yarn unplug -RA @semantic-release/commit-analyzer conventional-changelog-conventionalcommits import-from-esm`

---
This _did_. This allows `import-from-esm` to fall back to `import` when running via `yarn` and Yarn's PnP loader is injected and present in the runtime.

> .yarn/patches/import-from-esm-npm-2.0.0-8866147795.patch
```diff
diff --git a/index.js b/index.js
index b1ef46f47347ccf7274275667ef6261abc27fb2b..c9d2d57fc9edc2d8dc5bca6666ed0ccb46b72c66 100644
--- a/index.js
+++ b/index.js
@@ -1,5 +1,6 @@
-import { createRequire } from 'node:module';
+import _module, { createRequire } from 'node:module';
 import { extname, resolve } from 'node:path';
+import process from 'node:process';
 import { fileURLToPath, pathToFileURL } from 'node:url';
 
 import createDebug from 'debug';
@@ -108,12 +109,24 @@ async function importFrom(fromDirectory, moduleId) {
 		}
 	}
 
+	let _error;
+
+	if (!loadedModule) {
+		const isUsingYarn = process.env.npm_config_user_agent?.startsWith('yarn') === true;
+		const isUsingPnp = 'findPnpApi' in _module && typeof _module.findPnpApi === 'function';
+		// if Yarn PnP, fallback to default loader
+		if (isUsingYarn && isUsingPnp) {
+			try { loadedModule = await import(moduleId); }
+			catch (error) { _error = error; }
+		}
+	}
+
 	if (!loadedModule) {
 		const errorString = `Cannot find module '${moduleId}'`;
 		debug(errorString);
-		const error = new Error(errorString);
-		error.code = 'MODULE_NOT_FOUND';
-		throw error;
+		const newError = new Error(errorString, { cause: _error });
+		newError.code = 'MODULE_NOT_FOUND';
+		throw newError;
 	}
 
 	debug(`Successfully loaded module '${moduleId}' from '${fromDirectory}'`);
@@ -124,7 +137,7 @@ async function importFrom(fromDirectory, moduleId) {
 importFrom.silent = async function (fromDirectory, moduleId) {
 	try {
 		return await importFrom(fromDirectory, moduleId);
-	} catch {}
+	} catch { }
 };
 
 export default importFrom;

```

Edit 2: And then I somehow broke it.
Edit 3: Found the issue. Updated the above patch.
```ts
const isUsingPnp = 'findPnpApi ' in _module && typeof _module.findPnpApi === 'function';
                              ^
```
Edit 4:
[The recommended method of checking if operating under PnP](https://yarnpkg.com/advanced/pnpapi#processversionspnp):
```ts
const isUsingPnp = !!process.versions.pnp['pnp']
```

```sh
> echo "console.log(process.versions['pnp']);" > tmp.ts
> node tmp.ts
undefined
> yarn node tmp.ts
3
```
